/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HomelessPeople;

import Business.Enterprise.Enterprise;
import Business.Food.Food;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Refrigerator.drawer;
import Business.Refrigerator.refrigerator;
import Business.Report.Report;
import Business.UserAccount.UserAccount;
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Astha Sharma
 */
public class HomelessPersonalUIJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomelessPersonalUIJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private Organization homelessOrg;
    private Enterprise enterprise;
    private Network city;
    private refrigerator r;
    public HomelessPersonalUIJPanel(JPanel userProcessContainer,UserAccount useraccount,Organization homelessOrg,Enterprise enterprise,Network city,refrigerator r) {
        initComponents();
        this.city = city;
        this.enterprise = enterprise;
        this.homelessOrg = homelessOrg;
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.useraccount = useraccount;
        this.r = r;
        this.refriLbl.setText(r.getAddress());
        popDrawer();
    }
    
    public void popDrawer(){
        cbDrawers.removeAllItems();
        for(drawer d:r.getDrawers()){
            cbDrawers.addItem(d);
        }
    }
    
    public void popItem(drawer d){
        cbFood.removeAllItems();
        for(Food f:d.getFoodList().getFoodlist()){
            cbFood.addItem(f);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbDrawer = new javax.swing.JLabel();
        cbDrawers = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbFood = new javax.swing.JComboBox();
        getBtn = new javax.swing.JButton();
        btnSpeak = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        refriLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Logged in Successfully!");

        lbDrawer.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbDrawer.setText("Select Drawer:");

        cbDrawers.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbDrawers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDrawersActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Select Item: ");

        cbFood.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFoodActionPerformed(evt);
            }
        });

        getBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getBtn.setText("GET ITEM");
        getBtn.setEnabled(false);
        getBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBtnActionPerformed(evt);
            }
        });

        btnSpeak.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSpeak.setText("SPEAK");
        btnSpeak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeakActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Refrigerator:");

        refriLbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        refriLbl.setText("<value>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDrawer)
                            .addComponent(jLabel3))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDrawers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbFood, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSpeak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refriLbl)))))
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpeak)
                    .addComponent(jLabel2)
                    .addComponent(refriLbl))
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDrawers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDrawer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(getBtn)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbDrawersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDrawersActionPerformed
        // TODO add your handling code here:
        drawer d = (drawer)cbDrawers.getSelectedItem();
        if(d != null){
            popItem(d);
        }
    }//GEN-LAST:event_cbDrawersActionPerformed

    private void getBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBtnActionPerformed
        // TODO add your handling code here:
        drawer d = (drawer)cbDrawers.getSelectedItem();
        Food f = (Food)cbFood.getSelectedItem();
        d.getFoodList().getFoodlist().remove(f);
        popItem(d);
        JOptionPane.showMessageDialog(null,"Enjoy your food and thanks to the donor useraccount : "+f.getDonor());
        getBtn.setEnabled(false);
        Report report = new Report();
        report.setFood(f);
        report.setRefrigerator(r);
        report.setUser(useraccount);
        city.getReportList().add(report);
    }//GEN-LAST:event_getBtnActionPerformed

    private void cbFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFoodActionPerformed
        // TODO add your handling code here:
        Food f = (Food)cbFood.getSelectedItem();
        if(f!=null){
            this.getBtn.setEnabled(true);
        }
    }//GEN-LAST:event_cbFoodActionPerformed

    private static final String VOICENAME="kevin16";
    private void btnSpeakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeakActionPerformed
        // TODO add your handling code here:
        Voice voice;
        VoiceManager vm=VoiceManager.getInstance();
        voice=vm.getVoice(VOICENAME);
        drawer d = (drawer)cbDrawers.getSelectedItem();
        Food f = (Food)cbFood.getSelectedItem();

        voice.allocate();
        try
        {
            voice.speak("Refrigerator at     "+r.getAddress());
            voice.speak(String.valueOf("The drawer number     "+d.getDrawerId()));
            voice.speak("There are     ");
            for(Food fs:d.getFoodList().getFoodlist()){
                voice.speak(fs.getQuantity() + "     " +fs.getName());
            }
            voice.speak("     in it");
        }
        catch(Exception ex)
        {
            voice.speak("Please try after some time!");
        }
    }//GEN-LAST:event_btnSpeakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpeak;
    private javax.swing.JComboBox cbDrawers;
    private javax.swing.JComboBox cbFood;
    private javax.swing.JButton getBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbDrawer;
    private javax.swing.JLabel refriLbl;
    // End of variables declaration//GEN-END:variables
}
