/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.Business;
import Business.Network.Network;
import Business.Report.Report;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 帅的一匹
 */
public class ViewReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewReport
     */
    private JPanel userProcessContainer;
    private Business business;
    public ViewReportJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        popCom();
    }
    
    private void popCom(){
        networkCb.removeAllItems();
        for(Network n: business.getNetworkList()){
            networkCb.addItem(n);
        }
    }
    
    private void popTbl(Network n){
        DefaultTableModel dtm=(DefaultTableModel)reportTbl.getModel();
        dtm.setRowCount(0);
        for(Report r:n.getReportList()){
            Object[] row = new Object[5];
            row[0] = r;
            row[1] = r.getUser();
            row[2] = r.getRefrigerator().getRefrigeratorId();
            row[3] = r.getFood();
            row[4] = r.getFood().getDonor();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reportTbl = new javax.swing.JTable();
        networkCb = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        Btnsearch = new javax.swing.JButton();
        txtquantity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        reportTbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        reportTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Report Date", "Homeless User", "RefrigeratorId", "Food", "Donor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reportTbl);
        if (reportTbl.getColumnModel().getColumnCount() > 0) {
            reportTbl.getColumnModel().getColumn(0).setResizable(false);
            reportTbl.getColumnModel().getColumn(1).setResizable(false);
            reportTbl.getColumnModel().getColumn(2).setResizable(false);
            reportTbl.getColumnModel().getColumn(3).setResizable(false);
            reportTbl.getColumnModel().getColumn(4).setResizable(false);
        }

        networkCb.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        networkCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkCbActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Btnsearch.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Btnsearch.setText("Search");
        Btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsearchActionPerformed(evt);
            }
        });

        txtquantity.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Quantity >=");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btnsearch))
                    .addComponent(networkCb, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(networkCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Btnsearch)
                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void networkCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkCbActionPerformed
        // TODO add your handling code here:
        Network n = (Network)networkCb.getSelectedItem();
        if(n!=null){
            popTbl(n);
            Btnsearch.setEnabled(true);
        }
    }//GEN-LAST:event_networkCbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsearchActionPerformed
        // TODO add your handling code here:
        txtquantity.setText("");
        try{
            Integer.parseInt(txtquantity.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please enter integer!");
        }
        Network n = (Network)networkCb.getSelectedItem();
        int quantity = Integer.parseInt(txtquantity.getText());
        for(Report r: n.getReportList()){
            if(r.getFood().getQuantity() >= quantity){
                ReportDetailJPanel detail = new ReportDetailJPanel(userProcessContainer, r);
                userProcessContainer.add(detail);
                CardLayout layout=(CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        }
        Btnsearch.setEnabled(false);
        
    }//GEN-LAST:event_BtnsearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnsearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox networkCb;
    private javax.swing.JTable reportTbl;
    private javax.swing.JTextField txtquantity;
    // End of variables declaration//GEN-END:variables
}
