/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DelivererRole;

import Business.Network.Network;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FoodStorageEnterprise;
import Business.Food.Food;
import Business.Organization.DeliveryOrganization;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.Refrigerator.drawer;
import Business.Refrigerator.refrigerator;
import Business.UserAccount.UserAccount;
import Business.Workqueue.DeliverWorkRequest;
import Business.Workqueue.WorkRequest;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Astha Sharma
 */
public class DelivererWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DelivererWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private Organization deliverOrg;
    private Enterprise enterprise;
    private Network city;
    
    public DelivererWorkAreaJPanel(JPanel userProcessContainer,UserAccount useraccount,Organization deliverOrg,Network city,Enterprise enterprise) {
        initComponents();
        this.deliverOrg = (DeliveryOrganization)deliverOrg;
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.useraccount = useraccount;
        this.city = city;
        popTbl();
        popTbl2();
        popCom();
    }
    
    public void popCom(){
        this.cbFoodStorage.removeAllItems();;
        for(Enterprise e : city.getEnterpriseDir().getEnterpriseList()){
            if(e.getEnterpriseType() == Enterprise.EnterpriseType.FoodStorage){
                cbFoodStorage.addItem(e);
            }
        }
    }
    public void popCom2(refrigerator re){
        this.WRCbx.removeAllItems();
        for(drawer d:re.getDrawers()){
                WRCbx.addItem(d);
        }
    }
    public void popTbl2(){
        DefaultTableModel dtm2 = (DefaultTableModel)tblWork2.getModel();
        dtm2.setRowCount(0);
        for(WorkRequest wq:this.city.getWorkqueue().getWorkRequestList()){
            if(wq.getWorktype()==WorkRequest.workType.Deliver && wq.getReceiver()== this.useraccount && wq.getStatus()=="Undelivered"&&((DeliverWorkRequest)wq).hasRef()){
                Object[] row2 =new Object[3];
                row2[0]=wq.getWorkId();
                row2[1]=wq.getFood();
                row2[2]=((DeliverWorkRequest)wq).getRefrigerator();
                dtm2.addRow(row2);
            }
    }
    }
    public void popTbl(){
        DefaultTableModel dtm = (DefaultTableModel)tblWork.getModel();
        dtm.setRowCount(0);
        for(WorkRequest wq:this.city.getWorkqueue().getWorkRequestList()){
            if(wq.getWorktype()==WorkRequest.workType.Deliver && wq.getReceiver()== this.useraccount && wq.getStatus()=="Undelivered"){
                Object[] row = new Object[5];
                row[0]=wq.getFood().getFoodId();
                row[1]=wq;
                row[2]=wq.getFood().getDonor();
                row[3]=wq.getFood().getExpirationDate();
                row[4]=wq.getFood().getFrom();
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProcess = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWork = new javax.swing.JTable();
        cbFoodStorage = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblWork2 = new javax.swing.JTable();
        btnProcess1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        WRCbx = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(0, 153, 153));

        btnProcess.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        tblWork.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblWork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FoodId", "Food Name", "Donor", "ExpirationTime", "From"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWork);
        if (tblWork.getColumnModel().getColumnCount() > 0) {
            tblWork.getColumnModel().getColumn(0).setResizable(false);
            tblWork.getColumnModel().getColumn(1).setResizable(false);
            tblWork.getColumnModel().getColumn(2).setResizable(false);
            tblWork.getColumnModel().getColumn(3).setResizable(false);
            tblWork.getColumnModel().getColumn(4).setResizable(false);
        }

        cbFoodStorage.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Choose the foodstorage:");

        tblWork2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblWork2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "FoodId", "Food", "Refrigerator"
            }
        ));
        tblWork2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWork2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblWork2);

        btnProcess1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnProcess1.setText("Process");
        btnProcess1.setEnabled(false);
        btnProcess1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcess1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Choose the drawer:");

        WRCbx.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        WRCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WRCbxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(183, 183, 183))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbFoodStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(201, 201, 201)
                            .addComponent(btnProcess))
                        .addComponent(WRCbx, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(106, 106, 106)
                            .addComponent(btnProcess1))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFoodStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcess))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnProcess1))
                .addGap(18, 18, 18)
                .addComponent(WRCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int r = this.tblWork.getSelectedRow();
        FoodStorageEnterprise fs = (FoodStorageEnterprise)cbFoodStorage.getSelectedItem();
        if(r>=0){
            WorkRequest wq = (WorkRequest)tblWork.getValueAt(r, 1);
            wq.setStatus("Delivered");
            wq.setResolveDate(new Date());
            wq.getFood().setFrom(enterprise);
            fs.getFoodlist().getFoodlist().add(wq.getFood());
            JOptionPane.showMessageDialog(null, r);
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnProcess1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcess1ActionPerformed
        int r=tblWork2.getSelectedRow();
        if(r>=0){
            Food f=(Food)tblWork2.getValueAt(r, 1);
            ((drawer)this.WRCbx.getSelectedItem()).getFoodList().getFoodlist().add(f);
        
            JOptionPane.showMessageDialog(null, "Put food successfully !");
            
        }

    }//GEN-LAST:event_btnProcess1ActionPerformed

    private void WRCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WRCbxActionPerformed
        if(((drawer)WRCbx.getSelectedItem())!=null){
            btnProcess1.setEnabled(true);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_WRCbxActionPerformed

    private void tblWork2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWork2MouseClicked
        int rr = tblWork2.getSelectedRow();
        if(rr>=0){
            refrigerator re=(refrigerator)tblWork2.getValueAt(rr, 2);
            popCom2(re);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_tblWork2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox WRCbx;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnProcess1;
    private javax.swing.JComboBox cbFoodStorage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblWork;
    private javax.swing.JTable tblWork2;
    // End of variables declaration//GEN-END:variables
}
